### ISSUE TITLE
How to choose the vertices of SMPL model

### ISSUE THREAD

**Issue by 2382752230** [MarilynKeller/SMPL2AddBiomechanics#11]
Hi, thank you for your excellent work.

I'm new to this and I want to know how to get the vertices number of the SMPL model and where the vertices correspond to the body. For example, in bsm_markers.yaml, how do I get the mapping of anatomy markers to vertex serial numbers? Is the vertices sequence number obtained by visualization software? Can you answer it for me?

Thank you in advance for your help.
@MarilynKeller

**Comment by MarilynKeller** [comment]
Hi, the SMPL model has 6080. 

To know the index of a vertex, you can export the SMPL mesh, open it in [Meshlab](https://www.meshlab.net/), click in the "i" icon then click a triangle from the SMPL mesh
<img width="762" alt="image" src="https://github.com/user-attachments/assets/af11f1d3-3a05-434d-ad9e-92663d962eb1">

**Comment by 2382752230** [comment]
Thank you very much for your answer, I will close this question.
