### ISSUE TITLE
ModuleNotFoundError: No module named 'aitviewer.renderables.markers'

### ISSUE THREAD

**Issue by shenghuodehezuo** [MarilynKeller/SMPL2AddBiomechanics#3]
I looked at all versions of aitviewer and this markers file was not mentioned.

**Comment by shenghuodehezuo** [comment]
sorry i found it in your repo

**Comment by dosbelluno** [comment]
Where did you find it...? I can't find that...

**Comment by MarilynKeller** [comment]
This is not included in the base aitviewer repo, but in my fork aitviewer-skel : https://github.com/MarilynKeller/aitviewer-skel/blob/b6c15b77961b638e199f9ec7f03161e78aed6d16/aitviewer/renderables/markers.py

**Comment by dosbelluno** [comment]
Thank you so much... 😭
